// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vacina_tracker_v4.Models;

#nullable disable

namespace vacina_tracker_v4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230429005931_M02")]
    partial class M02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vacina_tracker_v4.Models.LinkDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MembroId")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VacinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.HasIndex("VacinaId");

                    b.ToTable("LinkDto");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomeMembroFamilia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VacinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VacinaId");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuários");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.UsuarioMembros", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("MembroId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "MembroId");

                    b.HasIndex("MembroId");

                    b.ToTable("Usuário Membros");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Vacina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataProxAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dose")
                        .HasColumnType("int");

                    b.Property<int>("NomeVacina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.LinkDto", b =>
                {
                    b.HasOne("vacina_tracker_v4.Models.Membro", null)
                        .WithMany("Links")
                        .HasForeignKey("MembroId");

                    b.HasOne("vacina_tracker_v4.Models.Vacina", null)
                        .WithMany("Links")
                        .HasForeignKey("VacinaId");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Membro", b =>
                {
                    b.HasOne("vacina_tracker_v4.Models.Vacina", "Vacinas")
                        .WithMany("Membros")
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.UsuarioMembros", b =>
                {
                    b.HasOne("vacina_tracker_v4.Models.Membro", "Membro")
                        .WithMany("Usuarios")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vacina_tracker_v4.Models.Usuario", "Usuario")
                        .WithMany("Membros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Membro", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Usuario", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("vacina_tracker_v4.Models.Vacina", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
